type: rule
name: external_monitoring_integration_rule
description: This rule triggers actions based on notifications from external monitoring systems.
enabled: true
trigger:
  type: webhook
  parameters:
    url: "https://your-external-monitoring-system.com/webhook"
    method: "POST"
    payload:
      event: "monitoring_alert"
      conditions:
        - condition: "critical"
          action: "send_discord_notification"
        - condition: "warning"
          action: "monitor_resources"
        - condition: "info"
          action: "generate_reports"
action:
  ref: "actions/external_monitoring_integration.yaml"
  parameters:
    notification_format: "json"
    alert_types:
      - critical
      - warning
      - info