rules/malware_detection_rule.yaml
---
name: "Malware Detection Rule"
description: "Triggers malware detection actions based on scheduled scans."
enabled: true
trigger:
  type: "schedule"
  parameters:
    cron: "0 * * * *"  # Every hour
action:
  ref: "actions/malware_detection.yaml"
  parameters:
    notification_channel: "discord"  # Send notifications to Discord
    alert_level: "critical"  # Set alert level for detected threats
    log_details: true  # Log details of the detection process
    scan_interval: "1h"  # Interval for scanning for malware