type: "rule"
name: "Network Management Rule"
description: "Triggers network management actions based on bandwidth usage."
enabled: true
trigger:
  type: "sensor"
  ref: "sensors.network_activity_sensor"
  parameters:
    threshold: 80
    comparison: "greater_than"
action:
  ref: "actions.network_management"