---
name: advanced_cache_cleaning_rule
description: This rule triggers the advanced cache cleaning action based on administrator commands.
enabled: true
trigger:
  type: core.st2.webhook
  parameters:
    url: clean_cache
criteria:
  trigger.parameters.cache_type:
    type: "equals"
    pattern: "kernel|inode/dentry|buffer"
action:
  ref: system_monitoring.advanced_cache_cleaning
  parameters:
    cache_type: "{{trigger.parameters.cache_type}}"
    confirmation: "{{trigger.parameters.confirmation}}"
