type: rule
name: advanced_cache_cleaning_rule
description: This rule triggers the advanced cache cleaning action based on administrator commands.
enabled: true
trigger:
  type: command
  parameters:
    command: clean_cache
    description: Command to initiate advanced cache cleaning.
    required_parameters:
      - cache_type
      - confirmation
action:
  ref: advanced_cache_cleaning
  parameters:
    cache_type: "{{trigger.parameters.cache_type}}"
    confirmation: "{{trigger.parameters.confirmation}}"