<<<<<<< HEAD
---
name: "automatic_recovery_rule"
description: "Triggers automatic recovery actions for failed services or containers."
enabled: true
trigger:
  type: "core.st2.Sensor"
  parameters:
    ref: "resource_monitoring_sensor"
criteria:
  trigger.parameters.service_failed:
    type: "equals"
    pattern: true
action:
  ref: "system_monitoring.automatic_recovery"
  parameters:
    service_name: "{{trigger.parameters.service_name}}"
    retry_count: 3
    notification_channel: "discord"
=======
type: "rule"
name: "Automatic Recovery Rule"
description: "Triggers automatic recovery actions for failed services or containers."
enabled: true
trigger:
  type: "sensor"
  sensor: "resource_monitoring_sensor"
  criteria:
    - condition: "service_failed"
      threshold: 1
action:
  ref: "automatic_recovery"
>>>>>>> 4b5c43c (move file)
