type: rule
name: clean_cache
description: Rule to trigger cache cleaning actions based on specific conditions.
enabled: true
trigger:
  type: sensor
  ref: clean_cache_sensor
action:
  ref: actions.clean_cache
  parameters:
    cache_type: "temporary"  # Example parameter, can be adjusted based on requirements
    notify_discord: true      # Notify Discord after cleaning cache
    log_results: true          # Log the results of the cache cleaning action