type: rule
name: detect_malware
description: Detects suspicious processes and triggers notifications to administrators.
enabled: true
trigger:
  type: sensor
  name: anomaly_detection_sensor
action:
  ref: actions.detect_malware
  parameters:
    notification_channel: discord
    severity: high
    message: "Malware detected! Please investigate immediately."