name: Detect Zombie Processes
description: This rule detects zombie processes and triggers the corresponding action.
enabled: true
trigger:
  type: sensor
  ref: resource_monitoring_sensor
  parameters:
    event: zombie_process_detected
action:
  ref: detect_zombie_processes.py
  parameters:
    notification_channel: discord
    log_action: true
    threshold: 1