type: rule
name: dynamic_priority_management_rule
description: This rule triggers dynamic priority management based on resource usage and administrator commands.
enabled: true
trigger:
  type: sensor
  ref: process_monitoring_sensor
  parameters:
    resource_usage_threshold: 
      cpu: 85
      ram: 80
      disk: 90
    action: dynamic_priority_management
    notification: send_discord_notification
    conditions:
      - process_running_time: 300  # in seconds
      - high_resource_usage: true
      - admin_command_received: true
action:
  ref: actions.dynamic_priority_management
  parameters:
    priority_adjustment: true
    notify_admin: true