---
name: dynamic_priority_management_rule
description: This rule triggers dynamic priority management based on resource usage and administrator commands.
enabled: true
trigger:
  type: core.st2.Sensor
  parameters:
    ref: process_monitoring_sensor
criteria:
  trigger.parameters.resource_usage_threshold.cpu:
    type: "gt"
    pattern: 85
  trigger.parameters.resource_usage_threshold.ram:
    type: "gt"
    pattern: 80
  trigger.parameters.resource_usage_threshold.disk:
    type: "gt"
    pattern: 90
action:
  ref: system_monitoring.dynamic_priority_management
  parameters:
    process_name: "{{trigger.parameters.process_name}}"
    action: "{{trigger.parameters.action}}"
    priority_level: "{{trigger.parameters.priority_level}}"
