---
name: external_monitoring_integration_rule
description: This rule triggers actions based on notifications from external monitoring systems.
enabled: true
trigger:
  type: core.st2.webhook
  parameters:
    url: "https://discord.com/api/webhooks/1321090400580276275/RbQ0zS-Ig0ZrMaDUG4l1BrEnp7CoFptDWBu_imKPHEzS6VVEFffww9vTMUXlHytjI1se"
criteria:
  trigger.payload.event:
    type: "equals"
    pattern: "monitoring_alert"
action:
  ref: system_monitoring.send_discord_notification
  parameters:
    url: "https://discord.com/api/webhooks/1321090400580276275/RbQ0zS-Ig0ZrMaDUG4l1BrEnp7CoFptDWBu_imKPHEzS6VVEFffww9vTMUXlHytjI1se"
    message: "An alert has been received from the external monitoring system."
    username: "Monitoring Bot"
    avatar_url: "https://example.com/avatar.png"
