<<<<<<< HEAD
---
name: generate_reports_rule
description: Triggers report generation actions on a scheduled basis.
enabled: true
trigger:
  type: core.st2.CronTimer
  parameters:
    minute: 0
    hour: 0
    day_of_week: "*"
    day: "*"
    month: "*"
action:
  ref: actions.generate_reports
=======
type: "rule"
name: "generate_reports_rule"
description: "Triggers report generation actions on a scheduled basis."
enabled: true
trigger:
  type: "schedule"
  parameters:
    cron: "0 0 * * *"  # Daily at midnight
action:
  ref: "actions.generate_reports"
>>>>>>> 4b5c43c (move file)
