---
name: generate_reports_rule
description: Triggers report generation actions on a scheduled basis.
enabled: true
trigger:
  type: core.st2.CronTimer
  parameters:
    minute: 0
    hour: 0
    day_of_week: "*"
    day: "*"
    month: "*"
action:
  ref: actions.generate_reports
