type: rule
name: generate_reports
description: Generates daily and monthly reports on resource usage and optimization actions.
enabled: true
trigger:
  type: interval
  seconds: 86400  # Trigger daily
action:
  ref: actions.generate_reports
  parameters:
    report_type: daily

  - trigger:
      type: interval
      seconds: 2592000  # Trigger monthly
    action:
      ref: actions.generate_reports
      parameters:
        report_type: monthly