name: Log Actions
description: This rule logs all actions taken by the system, including process management and resource monitoring activities.
enabled: true
trigger:
  type: core.st2.trigger
  parameters:
    name: log_actions_trigger
action:
  ref: actions.log_actions
  parameters:
    message: "Action executed: {{ trigger.action }} at {{ trigger.timestamp }}"
    level: info
    timestamp: "{{ trigger.timestamp }}"