---
name: "Malware Detection Rule"
description: "Triggers malware detection actions based on scheduled scans."
enabled: true
trigger:
  type: core.st2.CronTimer
  parameters:
    minute: 0
    hour: "*"
    day_of_week: "*"
    day: "*"
    month: "*"
action:
  ref: "system_monitoring.malware_detection"
  parameters:
    notification_channel: "discord"
    alert_level: "critical"
    log_details: true
    scan_interval: "1h"
