<<<<<<< HEAD
=======
rules/malware_detection_rule.yaml
>>>>>>> 4b5c43c (move file)
---
name: "Malware Detection Rule"
description: "Triggers malware detection actions based on scheduled scans."
enabled: true
trigger:
<<<<<<< HEAD
  type: core.st2.CronTimer
  parameters:
    minute: 0
    hour: "*"
    day_of_week: "*"
    day: "*"
    month: "*"
action:
  ref: "system_monitoring.malware_detection"
  parameters:
    notification_channel: "discord"
    alert_level: "critical"
    log_details: true
    scan_interval: "1h"
=======
  type: "schedule"
  parameters:
    cron: "0 * * * *"  # Every hour
action:
  ref: "actions/malware_detection.yaml"
  parameters:
    notification_channel: "discord"  # Send notifications to Discord
    alert_level: "critical"  # Set alert level for detected threats
    log_details: true  # Log details of the detection process
    scan_interval: "1h"  # Interval for scanning for malware
>>>>>>> 4b5c43c (move file)
