name: Manage Zombie Processes
description: This rule manages identified zombie processes by triggering the corresponding action.
enabled: true
trigger:
  type: detect_zombie_processes
  parameters:
    # Add any specific parameters for the trigger if needed
action:
  ref: actions.manage_zombie_processes
  parameters:
    # Add any specific parameters for the action if needed
    notify_discord: true
    cleanup: true