---
name: manage_temp_files_rule
description: Rule to trigger management of temporary files based on system conditions.
enabled: true
trigger:
  type: core.st2.Sensor
  parameters:
    ref: resource_monitoring_sensor
    condition:
      - type: disk_usage
        threshold: 80
      - type: temp_file_age
        threshold: 30
action:
  ref: actions.manage_temp_files
  parameters:
    notify_discord: true
