name: Monitor Resources Rule
description: This rule triggers resource monitoring actions based on usage thresholds.
enabled: true
trigger:
  type: sensor
  ref: resource_monitoring_sensor
  parameters:
    cpu_threshold: 90
    ram_threshold: 80
    disk_threshold: 90
    network_activity_threshold: 1000
action:
  ref: actions.monitor_resources
  parameters:
    alert_level: critical
    notification_channel: discord