name: Monitor Energy Efficiency
description: This rule monitors energy efficiency and triggers actions based on the results.
enabled: true
trigger:
  type: sensor
  ref: monitor_energy_efficiency_sensor
criteria:
  - type: threshold
    threshold: 80
    comparison: greater_than
    attribute: energy_efficiency
action:
  ref: actions.monitor_energy_efficiency
  parameters:
    message: "Energy efficiency has dropped below the acceptable threshold. Please take necessary actions."