name: Monitor Process Time
description: Monitors processes that exceed normal execution time and triggers notifications.
enabled: true
trigger:
  type: process_time_monitor
  parameters:
    threshold: 300  # Threshold in seconds
action:
  ref: actions.monitor_process_time
  parameters:
    notification_channel: discord
    message: "Process {{trigger.process_name}} has exceeded the execution time limit of {{trigger.threshold}} seconds."