name: Monitor Resources
description: Rule to monitor system resources and trigger alerts based on customizable thresholds.
enabled: true
trigger:
  type: sensor.resource_monitoring_sensor
  parameters:
    resource: cpu
    threshold: "{{ threshold.cpu }}"
  type: sensor.resource_monitoring_sensor
  parameters:
    resource: ram
    threshold: "{{ threshold.ram }}"
  type: sensor.resource_monitoring_sensor
  parameters:
    resource: disk
    threshold: "{{ threshold.disk }}"
  type: sensor.resource_monitoring_sensor
  parameters:
    resource: network
    threshold: "{{ threshold.network }}"
action:
  ref: actions.monitor_resources
  parameters:
    cpu_threshold: "{{ threshold.cpu }}"
    ram_threshold: "{{ threshold.ram }}"
    disk_threshold: "{{ threshold.disk }}"
    network_threshold: "{{ threshold.network }}"