---
name: multithreading_optimization_rule
description: This rule triggers the multithreading optimization action based on analysis results.
enabled: true
trigger:
  type: core.st2.IntervalTimer
  parameters:
    unit: seconds
    delta: 3600
action:
  ref: system_monitoring.multithreading_optimization
  parameters:
    threshold: 80
    notification_channel: discord
