---
name: "Network Management Rule"
description: "Triggers network management actions based on bandwidth usage."
enabled: true
trigger:
  type: core.st2.Sensor
  parameters:
    ref: sensors.network_activity_sensor
    threshold: 80
    comparison: "greater_than"
action:
  ref: actions.network_management
  parameters:
    alert_level: critical
    notification_channel: discord
