type: "rule"
name: "Optimize Multithreading"
description: "This rule triggers the optimization of multithreading based on resource usage."
enabled: true
trigger:
  type: "sensor"
  ref: "resource_monitoring_sensor"
  parameters:
    threshold: "high_cpu_usage"
action:
  ref: "optimize_multithreading"
  parameters:
    optimization_level: "recommended"