---
name: power_saving_mode_rule
description: Rule to trigger power-saving mode actions based on system status.
enabled: true
trigger:
  type: core.st2.Sensor
  parameters:
    ref: resource_monitoring_sensor
criteria:
  trigger.parameters.system_status:
    type: "equals"
    pattern: "on_battery"
action:
  ref: system_monitoring.activate_power_saving_mode
  parameters:
    notification_channel: discord
