---
name: "Process Time Monitoring Rule"
description: "Triggers monitoring actions for processes that exceed normal execution time."
enabled: true
trigger:
  type: "core.st2.Sensor"
  parameters:
    ref: "process_monitoring_sensor"
    threshold: "300" # Time in seconds to consider a process long-running
action:
  ref: "actions.process_time_monitoring"
  parameters:
    notification_channel: "discord" # Channel to send notifications
    alert_message: "Process {{ trigger.parameters.process_name }} has exceeded the normal execution time of {{ trigger.parameters.threshold }} seconds."
