type: "rule"
name: "Process Time Monitoring Rule"
description: "Triggers monitoring actions for processes that exceed normal execution time."
enabled: true
trigger:
  type: "sensor.process_monitoring_sensor"
  parameters:
    threshold: "300"  # Time in seconds to consider a process long-running
action:
  ref: "actions/process_time_monitoring.yaml"
  parameters:
    notification_channel: "discord"  # Channel to send notifications
    alert_message: "Process {{ process_name }} has exceeded the normal execution time of {{ threshold }} seconds."