name: Restart Docker Containers
description: This rule triggers the restart of Docker containers that fail and sends notifications to administrators.
enabled: true
trigger:
  type: core.st2.trigger
  parameters:
    name: docker_container_failed
action:
  ref: actions.restart_docker
  parameters:
    container_name: "{{trigger.container_name}}"
    reason: "{{trigger.reason}}"
notify:
  type: discord
  parameters:
    message: "Docker container {{trigger.container_name}} has failed and has been restarted due to {{trigger.reason}}."