name: Self Heal Rule
description: This rule triggers self-healing actions when specific conditions are met.
enabled: true
trigger:
  type: sensor
  ref: anomaly_detection_sensor
  parameters:
    condition: "anomaly_detected"
action:
  ref: self_heal
  parameters:
    message: "Self-healing action triggered due to detected anomaly."