<<<<<<< HEAD
---
=======
format: yaml
>>>>>>> 4b5c43c (move file)
name: self_healing_rule
description: Rule to trigger self-healing actions for simple issues.
enabled: true
trigger:
<<<<<<< HEAD
  type: core.st2.Sensor
  parameters:
    ref: process_monitoring_sensor
criteria:
  trigger.parameters.simple_issue_detected:
    type: "equals"
    pattern: 1
=======
  type: sensor
  ref: process_monitoring_sensor
  criteria:
    - condition: "simple_issue_detected"
      threshold: 1
>>>>>>> 4b5c43c (move file)
action:
  ref: self_healing
  parameters:
    notify_admin: true
<<<<<<< HEAD
    log_results: true
=======
    log_results: true
>>>>>>> 4b5c43c (move file)
