---
name: self_healing_rule
description: Rule to trigger self-healing actions for simple issues.
enabled: true
trigger:
  type: core.st2.Sensor
  parameters:
    ref: process_monitoring_sensor
criteria:
  trigger.parameters.simple_issue_detected:
    type: "equals"
    pattern: 1
action:
  ref: self_healing
  parameters:
    notify_admin: true
    log_results: true
