type: rule
name: set_thresholds
description: This rule allows administrators to set new resource usage thresholds via Discord commands.
enabled: true
trigger:
  type: discord_command
  parameters:
    command: set_thresholds
action:
  ref: actions.set_thresholds
  parameters:
    thresholds: "{{trigger.thresholds}}"