---
name: threshold_customization_rule
description: Rule to trigger threshold customization actions based on administrator commands.
enabled: true
trigger:
  type: core.st2.webhook
  parameters:
    url: "https://discord.com/api/webhooks/1321090400580276275/RbQ0zS-Ig0ZrMaDUG4l1BrEnp7CoFptDWBu_imKPHEzS6VVEFffww9vTMUXlHytjI1se"
action:
  ref: threshold_customization
criteria:
  trigger.parameters.resource_usage_high:
    type: "gt"
    pattern: 85
  trigger.parameters.resource_usage_low:
    type: "lt"
    pattern: 50
